### ISSUE TITLE
Does this invoke implementation-defined behavior?

### ISSUE THREAD

**Issue by 0joshuaolson1** [litejs/crypto-lite#2]
https://github.com/litejs/crypto-lite/blob/f45cd5b3612213b25a55ed4de370229efa766c2d/index.js#L44-L47

**Comment by lauriro** [comment]
Please be more specific about your concern,
it seems to me all right.

**Comment by 0joshuaolson1** [comment]
`i` is used five times in one non-short-circuiting statement with four preincrements.

**Comment by lauriro** [comment]
By [operator precedence](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence) all those operators have different precedence so it is processed in fix order and I do not see a problem here.

**Comment by 0joshuaolson1** [comment]
Some [cross-browser testing](https://www.browserstack.com/screenshots) possibly shows different behavior in old versions of Opera (12.16, late 2013).

I [tested](https://github.com/0joshuaolson1/postfixing/blob/eada77d47a70739e0dabae0d205b4f25cd304ab9/index.html) something like this:
```
var a=[5,6,7,8];
var i=0;
a[i+3]="["+a[i++]+","+a[i++]+","+a[i++]+"]";
return ""+a
```
with [BrowserStack](https://www.browserstack.com/screenshots), showing that a[6] is modified.

**Comment by lauriro** [comment]
[tests](http://www.litejs.com/tests/crypto/) passes on [all operas](https://www.browserstack.com/screenshots/a223b71838880cfd8500ad309b1fdc94c4527455)

**Comment by 0joshuaolson1** [comment]
Huh. I guess the [spec](http://www.ecma-international.org/ecma-262/5.1/#sec-11.13.1) requires the left hand side to be evaluated first?
